repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff
        language: system
        types: [python]
        args: ["check", "--fix", "."]

      - id: ruff-format
        name: ruff format
        entry: ruff
        language: system
        types: [python]
        args: ["format", "."]

      - id: pyright
        name: pyright
        entry: pyright
        language: node
        types: [python]
        args: ["src/"]
        pass_filenames: false
