# Ruff configuration for nvi-notify project
line-length = 88
indent-width = 4
target-version = "py312"

# 格式化配置
[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint]
select = [
    "I",  # isort
    "N",  # pep8-naming
    "UP", # pyupgrade
    "F",  # PyFlakes
    "PL", # Pylint
    # "YTT",   # flake8-2020
    "ANN", # flake8-annotations
    # "S",     # flake8-bandit
    # "BLE",   # flake8-blind-except
    # "FBT",   # flake8-boolean-trap
    # "B",     # flake8-bugbear
    # "A",     # flake8-builtins
    # "COM",   # flake8-commas
    # "C4",    # flake8-comprehensions
    # "DTZ",   # flake8-datetimez
    # "T10",   # flake8-debugger
    # "EXE",   # flake8-executable
    # "ISC",   # flake8-implicit-str-concat
    # "ICN",   # flake8-import-conventions
    # "G",     # flake8-logging-format
    # "INP",   # flake8-no-pep420
    # "PIE",   # flake8-pie
    # "T20",   # flake8-print
    # "PYI",   # flake8-pyi
    # "PT",    # flake8-pytest-style
    "Q", # flake8-quotes
    # "RUF",   # Ruff-specific rules
    "SLF", # flake8-self
    # "SIM",   # flake8-simplify
    "TID", # flake8-tidy-imports
    # "ARG",   # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    # "ERA",   # eradicate
    # "PD",    # pandas-vet
    # "PGH",   # pygrep-hooks
    # "TRY",   # tryceratops
    # "FLY",   # flynt
    # "NPY",   # NumPy-specific rules
    # "AIR",   # Airflow
    # "PERF",  # Perflint
]
ignore = [
    "PLR", # Design related pylint codes
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.isort]
# known-first-party = ["src"]
combine-as-imports = true
force-wrap-aliases = true

[lint.per-file-ignores]
"src/nvi_notify/entity/task_info.py" = ["N815"]
