# Ruff configuration for nvi-notify project

line-length = 88
indent-width = 4

# Enable PyFlakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
select = ["E4", "E7", "E9", "F"]
extend-select = [
    "I",     # isort
    # "N",     # pep8-naming
    # "UP",    # pyupgrade
    # "YTT",   # flake8-2020
    # "ANN",   # flake8-annotations
    # "S",     # flake8-bandit
    # "BLE",   # flake8-blind-except
    # "FBT",   # flake8-boolean-trap
    # "B",     # flake8-bugbear
    # "A",     # flake8-builtins
    # "COM",   # flake8-commas
    # "C4",    # flake8-comprehensions
    # "DTZ",   # flake8-datetimez
    # "T10",   # flake8-debugger
    # "EXE",   # flake8-executable
    # "ISC",   # flake8-implicit-str-concat
    # "ICN",   # flake8-import-conventions
    # "G",     # flake8-logging-format
    # "INP",   # flake8-no-pep420
    # "PIE",   # flake8-pie
    # "T20",   # flake8-print
    # "PYI",   # flake8-pyi
    # "PT",    # flake8-pytest-style
    "Q",     # flake8-quotes
    # "RUF",   # Ruff-specific rules
    "SLF",   # flake8-self
    # "SIM",   # flake8-simplify
    "TID",   # flake8-tidy-imports
    # "ARG",   # flake8-unused-arguments
    "PTH",   # flake8-use-pathlib
    # "ERA",   # eradicate
    # "PD",    # pandas-vet
    # "PGH",   # pygrep-hooks
    # "PL",    # Pylint
    # "TRY",   # tryceratops
    # "FLY",   # flynt
    # "NPY",   # NumPy-specific rules
    # "AIR",   # Airflow
    # "PERF",  # Perflint
]
extend-ignore = [
    "PLR",   # Design related pylint codes
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"